neich/neuronumba

- neuronumba/observables/ph_fcd.py
Now the observables should always return a dictionary
> Small change: returns a dict

- neuronumba/observables/ph_fcd.py
Fixed the problem between neuronumba not accepting dicts as returned values.
> fixing dictionaries for the observable

- src/neuronumba/observables/insideout.py
added the InsideOut observable
> added the InsideOut observable

- examples/hopf_test.py
Reworked version of the example, with two models to choose
> Reworked version of the example, with two models to choose

- src/neuronumba/simulator/monitors.py
Fixed some bugs in this monitor
> Fix TemporalAverage monitor

- examples/README.md
- examples/global_coupling_fitting.py
Cleaned imports. Improved help for command line arguments
> Cleaned imports. Improved help for command line arguments

- examples/README.md
- examples/global_coupling_fitting.py
Fix small issue in global connectivity example and fix the README
> Small fixes for the examples

- examples/global_coupling_fitting.py
- src/neuronumba/simulator/models/montbrio.py
And added to the global coupling fitting example
> Added Montbrio model

- examples/gen_bold.py
- examples/global_coupling_fitting.py
Added TR as parameter and Montbrio model as option
> Small improvements on examples

- examples/global_coupling_fitting.py
- src/neuronumba/simulator/monitors.py
Fixed numba bug in TemporalAverage monitor, and fix incorrect comptation of bold for Hopf model
> Fix TemporalAverage monitor and global fitting example

- src/neuronumba/basic/attr.py
- src/neuronumba/simulator/models/deco2014.py
- src/neuronumba/simulator/models/model.py
- src/neuronumba/simulator/monitors.py
Model Deco2014: Added support for automatic FIC initialization. Use array version of clip() function
Fixed TemporalAverage monitor. Use sum and division to compute average. np.sum() does not work with axis attribute inside numba.
Improved Attr with mechanism to know if an attribute has been manually initialized or not. also refactoring of attribute initialization.
Small optimization in LinearCoupling Method by precomputing multiplication by global scaling variable
> Several fixes

- examples/README.md
- examples/gen_bold.py
- examples/global_coupling_fitting.py
Some improvements like adding new models, plotting and small fixes
> Examples improvements

- src/neuronumba/fitting/gec/__init__.py
- src/neuronumba/fitting/gec/fitting_gec.py
- src/neuronumba/observables/linear/linearfc.py
GEC computation is finally working. Had been compared with Irena's matlab code.
> GEC correction

- src/neuronumba/basic/attr.py
- src/neuronumba/observables/base_observable.py
- src/neuronumba/observables/fc.py
- src/neuronumba/observables/measures.py
- src/neuronumba/simulator/models/model.py
- src/neuronumba/tools/filters.py
> Several fixes and improvements

- examples/gen_bold.py
- examples/global_coupling_fitting.py
For the global coupling fitting example:  add optional band pass filter, add observable selection, change number of subjects as parameter, automatically detect if single point executions, add bold models as parameter
For the bold generator example: Use g and scaling. Add value of g to the figure
> Several improvements in global coupling fitting and bold generator examples

- examples/global_coupling_fitting.py
> Fix missing filters. Fix missing configure() call

- examples/papers/Deco2018/README.md
- examples/papers/Deco2018/deco2018.py
- examples/papers/Deco2018/serotonin2A.py
- examples/papers/README.md
And a first example for Deco 2018 paper on LSD
> Added paper examples folder

- examples/global_coupling_fitting.py
Also, fixed number of subjects initialization and added support for sweep of modelsxobservables
> Now using concurrent module instead of multiprocessing

- .gitignore
- src/neuronumba/observables/base_observable.py
Fixed surrogate generation and a comment
> Fixed surrogate generation and a comment

- .gitignore
- README.md
- examples/README.md
- examples/global_coupling_fitting.py
- src/neuronumba/observables/fc.py
- src/neuronumba/simulator/models/montbrio.py
Please, see the commits. Small fixes unrelated
> Several fixes (unrelated)

- examples/global_coupling_fitting.py
- examples/papers/Deco2018/deco2018.py
- src/neuronumba/tools/matlab_tricks.py
fixed Deco2018 J initialization to match results on the original paper...
> Fixed Deco2018

- examples/global_coupling_fitting.py
- src/neuronumba/simulator/simulator.py
t_warmup timepoints were removed TWICE (and some minor things)
> t_warmup timepoints were removed TWICE (and some minor things)

- .vscode/launch.json
- src/pyproject.toml
> Small updates and fixes

- src/neuronumba/simulator/models/deco2014.py
Added linear model (Jacobian) and changed a couple of variable names.
> Added linear model (Jacobian) and changed a couple of variable names.

- src/neuronumba/fitting/gec/fitting_gec.py
- src/neuronumba/observables/base_observable.py
- src/neuronumba/observables/fdt_off_eq.py
- src/neuronumba/observables/lagged_cov.py
- src/neuronumba/observables/turbulence2.py
Added off equilibrium FDT to the observables
> Added off equilibrium FDT to the observables

- examples/gec_example.py
- src/neuronumba/fitting/gec/__init__.py
- src/neuronumba/fitting/gec/fitting_gec.py
refactored model evaluation into a linear (and non-linear, but not implemented yet) mechanisms in GEC.
> refactored model evaluation into a linear mechanism in GEC

- examples/gen_bold.py
- examples/global_coupling_fitting.py
- src/neuronumba/basic/attr.py
- src/neuronumba/numba_tools/functions.py
- src/neuronumba/simulator/history.py
- src/neuronumba/simulator/integrators/euler.py
- src/neuronumba/simulator/models/__init__.py
- src/neuronumba/simulator/models/deco2014.py
- src/neuronumba/simulator/models/hopf.py
- src/neuronumba/simulator/models/model.py
- src/neuronumba/simulator/models/naskar2021.py
- src/neuronumba/simulator/models/zerlaut.py
- src/neuronumba/simulator/monitors.py
- src/neuronumba/simulator/simulator.py
- src/neuronumba/tools/loader.py
Improve model handling with new models added, enhanced documentation, and better parameter management. Optimize performance by adding caching to Numba JIT decorators and refactoring several methods for clarity and maintainability. Fix minor issues and improve data saving functionality in MATLAB format.
Read the datails in the commits
> Enhance models and optimize performance

- .vscode/launch.json
- examples/global_coupling_fitting.py
- src/neuronumba/simulator/models/deco2014.py
- src/neuronumba/simulator/models/zerlaut.py
- src/neuronumba/simulator/simulator.py
Enhance performance through Numba JIT compilation optimizations, add timing measurements for simulation runs, and update debugging configurations for improved usability.
> Optimize performance and debugging configurations

- examples/global_coupling_fitting.py
- src/neuronumba/numba_tools/functions.py
- src/neuronumba/observables/__init__.py
- src/neuronumba/observables/ph_fcd.py
- src/neuronumba/observables/phase_interaction_matrix.py
- src/neuronumba/observables/sw_fcd.py
Improve the `load_subjects_data` function to accept a maximum number of subjects and add a verbose flag for detailed output. Introduce Numba-optimized Pearson correlation functions for both 1D and 2D data. Refactor the `PhFCD` and `SwFCD` classes to enhance performance and clarity in matrix computations.
> Enhance subject loading and optimize correlation computations

- examples/global_coupling_fitting.py
- src/neuronumba/numba_tools/config.py
- src/neuronumba/numba_tools/functions.py
- src/neuronumba/simulator/history.py
- src/neuronumba/simulator/integrators/euler.py
- src/neuronumba/simulator/models/deco2014.py
- src/neuronumba/simulator/models/hopf.py
- src/neuronumba/simulator/models/model.py
- src/neuronumba/simulator/models/naskar2021.py
- src/neuronumba/simulator/models/zerlaut.py
- src/neuronumba/simulator/monitors.py
- src/neuronumba/simulator/simulator.py
Refactor output file handling for consistency and improve logging in the processing function. Update the argument parser to make the fMRI path optional. Introduce centralized Numba optimization settings for better performance across models and functions.
> Refactor output handling and optimize Numba settings

- src/neuronumba/tools/filters.py
Enhance clarity by adding descriptive documentation to the attributes of the BandPassFilter class.
> Improve documentation for BandPassFilter attributes

- .gitignore
- .vscode/launch.json
- examples/global_coupling_fitting.py
- src/neuronumba/tools/hdf.py
Improve multiprocessing support and error handling in the global coupling fitting script, add compatibility for older versions of the savemat function, and refine launch configurations for clarity and consistency. Additionally, update the .gitignore to exclude more files and directories.
> Enhance global coupling fitting script and update configurations

- examples/global_coupling_fitting.py
- src/neuronumba/basic/attr.py
- src/neuronumba/simulator/models/model.py
- src/neuronumba/simulator/models/montbrio.py
Introduce `set_attributes` and `get_attributes` methods for better attribute handling in the `HasAttr` class. Remove unused methods and unnecessary blank lines in the `Model` class for improved readability. Eliminate obsolete coupling strength attributes from the `Montbrio` class and refactor observable and model factories to enhance configurability and clarity.
> Enhance attribute management and clean up codebase. Added parameter explorstion to examples

- examples/global_coupling_fitting.py
Enhance ObservableConfig to support multiple distance measures, updating related factory functions and simulation processes accordingly. This change improves flexibility in distance calculations.
> Refactor ObservableConfig for multiple distance measures

- src/neuronumba/tools/filterps.py
Well, this: fixed a small bug in FiltPowSpetraVersion.v2015, improved error reporting (version)
> fixed small bug, improved error reporting

- src/neuronumba/fitting/gec/fitting_gec.py
Fixed minor bug (which broke BOLD Stephan)
> Fixed minor bug (which broke BOLD Stephan)
